version: "3.8"

services:
  app:
    image: getghosted/yassine-spring-app
    ports:
      - "9058:8080" # Expose your application port
    depends_on:
      - prometheus
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9092:9090"
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

    networks:
      - app-network


networks:
  app-network: