version: "3.8"

services:
  app:
    image: yassine-spring-app
    ports:
      - "9058:8080" # Expose your application port
    depends_on:
      - prometheus
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9092:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Mount your Prometheus config
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=15d' # Adjust retention as needed
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

    networks:
      - app-network


networks:
  app-network: